use CDMS_Rpt;

create table Public_WaterTemp (

	[ActivityId] [int] NOT NULL,
	[Name] [nvarchar](max) NULL,
	[Description] [nvarchar](max) NULL,
	[DatasetId] [int] NOT NULL,
	[SourceId] [int] NOT NULL,
	[LocationId] [int] NOT NULL,
	[UserId] [int] NOT NULL,
	[ActivityTypeId] [int] NOT NULL,
	[CreateDate] [datetime] NOT NULL,
	[ActivityDate] [datetime] NOT NULL,
	[InstrumentId] [int] NULL,
	[AccuracyCheckId] [int] NULL,
	[PostAccuracyCheckId] [int] NULL,
	[Timezone] [nvarchar](max) NULL,
	
	[ActivityQAStatusId] [int] NOT NULL,
	[ActivityQAStatusUserId] [int] NOT NULL,
	[ActivityQAStatusEffDt] [datetime] NOT NULL,
	[ActivityQAStatusComments] [nvarchar](max) NULL,
	[ActivityQAStatusName] [nvarchar](max) NULL,
	
	[HeaderId] [int] NOT NULL,
	[Technicians] [nvarchar](max) NULL,
	[Comments] [nvarchar](max) NULL,
	[CollectionType] [nvarchar](max) NULL,
	[DepthToWater] [float] NULL,
	[StaticWaterLevel] [float] NULL,
	[WeatherConditions] [nvarchar](max) NULL,
	[SamplePeriod] [nvarchar](max) NULL,
	[SampleTempUnit] [nvarchar](max) NULL,
	[HeaderByUserId] [int] NOT NULL,
	[HeaderEffDt] [datetime] NOT NULL,
	[FieldActivityType] [nvarchar](max) NULL,
	[DeployTime] [nvarchar](max) NULL,

	[DetailId] [int] NOT NULL,
	[ReadingDateTime] [datetime] NOT NULL,
	[WaterTemperature] [float] NULL,
	[WaterTemperatureF] [float] NULL,
	[WaterLevel] [float] NULL,
	[TempAToD] [float] NULL,
	[BatteryVolts] [float] NULL,
	[RowId] [int] NOT NULL,
	[RowStatusId] [int] NOT NULL,
	[DetailByUserId] [int] NOT NULL,
	[QAStatusId] [int] NOT NULL,
	[DetailEffDt] [datetime] NOT NULL,
	[AirTemperature] [float] NULL,
	[AirTemperatureF] [float] NULL,
	[GMTReadingDateTime] [datetime] NULL,
	[Conductivity] [float] NULL,
	[PSI] [float] NULL,
	[AbsolutePressure] [float] NULL,
	[WaterYearCalculated] [int] NULL
)