// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class adultweirdataset3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adultweirdataset3));
        
        string IMigrationMetadata.Id
        {
            get { return "201312112347453_adultweirdataset3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
