// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removefieldconfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removefieldconfig));
        
        string IMigrationMetadata.Id
        {
            get { return "201311202004164_remove-field-config"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
