// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class _08121 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_08121));
        
        string IMigrationMetadata.Id
        {
            get { return "201308121559363_0812-1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
