// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class controltypefield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(controltypefield));
        
        string IMigrationMetadata.Id
        {
            get { return "201312232209129_controltypefield"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
