// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ProjectDatesCanBeNull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProjectDatesCanBeNull));
        
        string IMigrationMetadata.Id
        {
            get { return "201308082246557_ProjectDatesCanBeNull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
