// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fieldpossiblevalues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fieldpossiblevalues));
        
        string IMigrationMetadata.Id
        {
            get { return "201311192140132_field-possiblevalues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
