// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class adultweirdataset2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adultweirdataset2));
        
        string IMigrationMetadata.Id
        {
            get { return "201312112344164_adultweirdataset2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
