// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class FilesController : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FilesController));
        
        string IMigrationMetadata.Id
        {
            get { return "201308061705296_FilesController"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
