// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class activities_models : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(activities_models));
        
        string IMigrationMetadata.Id
        {
            get { return "201311202247256_activities_models"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
