// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class appraisalprojecttype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appraisalprojecttype));
        
        string IMigrationMetadata.Id
        {
            get { return "201407291900317_appraisal-project-type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
