// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_fish_transport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_fish_transport));
        
        string IMigrationMetadata.Id
        {
            get { return "201404041743182_add_fish_transport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
