// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removeboolfromdetailfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeboolfromdetailfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201402242228514_removeboolfrom-detail-fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
