// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class moreappraisalfieldadditions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moreappraisalfieldadditions));
        
        string IMigrationMetadata.Id
        {
            get { return "201407291856263_more-appraisal-field-additions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
