// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class singlewaterbodyforlocationfix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(singlewaterbodyforlocationfix));
        
        string IMigrationMetadata.Id
        {
            get { return "201406022152400_single-waterbody-forlocation-fix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
