// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class UGRnewfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UGRnewfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201404242210153_UGR-newfields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
