// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class gmtreadingdatetimetowatertemp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gmtreadingdatetimetowatertemp));
        
        string IMigrationMetadata.Id
        {
            get { return "201406252208563_gmtreadingdatetime-towatertemp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
