// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_sex_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_sex_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201401282147253_update_sex_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
