// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addactivitypostaccuracycheck : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addactivitypostaccuracycheck));
        
        string IMigrationMetadata.Id
        {
            get { return "201406161854485_add-activity-post-accuracycheck"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
