// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addFinClip : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFinClip));
        
        string IMigrationMetadata.Id
        {
            get { return "201404102017282_addFinClip"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
