// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class userimageurl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userimageurl));
        
        string IMigrationMetadata.Id
        {
            get { return "201403172222348_user-imageurl"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
