// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class watertempoptionalwatertempvalues : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(watertempoptionalwatertempvalues));
        
        string IMigrationMetadata.Id
        {
            get { return "201405091915202_watertemp-optionalwatertempvalues"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
