// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fixwatertempfieldagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixwatertempfieldagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201406262303532_fix-watertemp-field-again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
