// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class updatewatertempfields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatewatertempfields));
        
        string IMigrationMetadata.Id
        {
            get { return "201406262247197_update-watertemp-fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
