// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class appraisalfields_additions : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appraisalfields_additions));
        
        string IMigrationMetadata.Id
        {
            get { return "201407241622052_appraisalfields_additions"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
