// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class tweakinstrument : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tweakinstrument));
        
        string IMigrationMetadata.Id
        {
            get { return "201405161742016_tweak-instrument"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
