// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class appraisaltable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(appraisaltable));
        
        string IMigrationMetadata.Id
        {
            get { return "201407011600197_appraisal-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
