// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class fieldchanges1_3_14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fieldchanges1_3_14));
        
        string IMigrationMetadata.Id
        {
            get { return "201401031650524_field-changes-1_3_14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
