// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class adultweir_fields_tostandards : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adultweir_fields_tostandards));
        
        string IMigrationMetadata.Id
        {
            get { return "201403072305289_adultweir_fields_tostandards"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
