// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class nullablegmtdatetime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullablegmtdatetime));
        
        string IMigrationMetadata.Id
        {
            get { return "201406262232141_nullable-gmt-datetime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
