// <auto-generated />
namespace services.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class aftermigrationaddfieldcategory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(aftermigrationaddfieldcategory));
        
        string IMigrationMetadata.Id
        {
            get { return "201405072221479_after-migration--add-field-category"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
