// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MeetTheNewViewSameAsTheOldView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MeetTheNewViewSameAsTheOldView));
        
        string IMigrationMetadata.Id
        {
            get { return "201510301826567_MeetTheNewViewSameAsTheOldView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
