// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addmdlresultstowaterqualitytable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addmdlresultstowaterqualitytable));
        
        string IMigrationMetadata.Id
        {
            get { return "201509022322186_Add mdlresults to water quality table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
