namespace services.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class sitkaclearthedecks : DbMigration
    {
        public override void Up()
        {
            //RenameTable(name: "dbo.ProjectInstruments", newName: "InstrumentProjects");
            //DropPrimaryKey("dbo.InstrumentProjects");
            //AddPrimaryKey("dbo.InstrumentProjects", new[] { "Instrument_Id", "Project_Id" });
            //CreateIndex("dbo.InstrumentAccuracyChecks", "InstrumentId");
            //CreateIndex("dbo.InstrumentAccuracyChecks", "UserId");
            //CreateIndex("dbo.Instruments", "OwningDepartmentId");
            //CreateIndex("dbo.Instruments", "InstrumentTypeId");
            //CreateIndex("dbo.Instruments", "UserId");
            //CreateIndex("dbo.Departments", "OrganizationId");
            //CreateIndex("dbo.Projects", "ProjectTypeId");
            //CreateIndex("dbo.Projects", "OrganizationId");
            //CreateIndex("dbo.Projects", "OwnerId");
            //CreateIndex("dbo.Users", "OrganizationId");
            //CreateIndex("dbo.Users", "DepartmentId");
            //CreateIndex("dbo.UserPreferences", "UserId");
            //CreateIndex("dbo.Files", "ProjectId");
            //CreateIndex("dbo.Files", "UserId");
            //CreateIndex("dbo.Files", "FileTypeId");
            //CreateIndex("dbo.Locations", "LocationTypeId");
            //CreateIndex("dbo.Locations", "WaterBodyId");
            //CreateIndex("dbo.Locations", "SdeFeatureClassId");
            //CreateIndex("dbo.Activities", "DatasetId");
            //CreateIndex("dbo.Activities", "SourceId");
            //CreateIndex("dbo.Activities", "LocationId");
            //CreateIndex("dbo.Activities", "UserId");
            //CreateIndex("dbo.Activities", "ActivityTypeId");
            //CreateIndex("dbo.Activities", "InstrumentId");
            //CreateIndex("dbo.Activities", "AccuracyCheckId");
            //CreateIndex("dbo.Activities", "PostAccuracyCheckId");
            //CreateIndex("dbo.Datasets", "DefaultRowQAStatusId");
            //CreateIndex("dbo.Datasets", "DatastoreId");
            //CreateIndex("dbo.DatasetFields", "DatasetId");
            //CreateIndex("dbo.DatasetFields", "FieldId");
            //CreateIndex("dbo.DatasetFields", "FieldRoleId");
            //CreateIndex("dbo.DatasetFields", "SourceId");
            //CreateIndex("dbo.DatasetFields", "InstrumentId");
            //CreateIndex("dbo.Fields", "FieldCategoryId");
            //CreateIndex("dbo.ActivityQAs", "QAStatusId");
            //CreateIndex("dbo.ActivityQAs", "UserId");
            //CreateIndex("dbo.AdultWeir_Detail", "ActivityId");
            //CreateIndex("dbo.AdultWeir_Detail", "ByUserId");
            //CreateIndex("dbo.AdultWeir_Detail", "QAStatusId");
            //CreateIndex("dbo.AdultWeir_Header", "ActivityId");
            //CreateIndex("dbo.AdultWeir_Header", "ByUserId");
            //CreateIndex("dbo.Appraisal_Detail", "ActivityId");
            //CreateIndex("dbo.Appraisal_Detail", "ByUserId");
            //CreateIndex("dbo.Appraisal_Detail", "QAStatusId");
            //CreateIndex("dbo.Appraisal_Header", "ActivityId");
            //CreateIndex("dbo.Appraisal_Header", "ByUserId");
            //CreateIndex("dbo.ArtificialProduction_Detail", "ActivityId");
            //CreateIndex("dbo.ArtificialProduction_Detail", "ByUserId");
            //CreateIndex("dbo.ArtificialProduction_Detail", "QAStatusId");
            //CreateIndex("dbo.ArtificialProduction_Header", "ActivityId");
            //CreateIndex("dbo.ArtificialProduction_Header", "ByUserId");
            //CreateIndex("dbo.CreelSurvey_Carcass", "ActivityId");
            //CreateIndex("dbo.CreelSurvey_Carcass", "ByUserId");
            //CreateIndex("dbo.CreelSurvey_Carcass", "QAStatusId");
            //CreateIndex("dbo.CreelSurvey_Detail", "DetailLocationId");
            //CreateIndex("dbo.CreelSurvey_Detail", "ActivityId");
            //CreateIndex("dbo.CreelSurvey_Detail", "ByUserId");
            //CreateIndex("dbo.CreelSurvey_Detail", "QAStatusId");
            //CreateIndex("dbo.CreelSurvey_Header", "ActivityId");
            //CreateIndex("dbo.CreelSurvey_Header", "ByUserId");
            //CreateIndex("dbo.FishTransport_Detail", "ActivityId");
            //CreateIndex("dbo.FishTransport_Detail", "ByUserId");
            //CreateIndex("dbo.FishTransport_Detail", "QAStatusId");
            //CreateIndex("dbo.FishTransport_Header", "ActivityId");
            //CreateIndex("dbo.FishTransport_Header", "ByUserId");
            //CreateIndex("dbo.MetadataProperties", "MetadataEntityId");
            //CreateIndex("dbo.WaterTemp_Detail", "ActivityId");
            //CreateIndex("dbo.WaterTemp_Detail", "ByUserId");
            //CreateIndex("dbo.WaterTemp_Detail", "QAStatusId");
            //CreateIndex("dbo.WaterTemp_Header", "ActivityId");
            //CreateIndex("dbo.WaterTemp_Header", "ByUserId");
            //CreateIndex("dbo.ProjectUsers", "Project_Id");
            //CreateIndex("dbo.ProjectUsers", "User_Id");
            //CreateIndex("dbo.LocationProjects", "Location_Id");
            //CreateIndex("dbo.LocationProjects", "Project_Id");
            //CreateIndex("dbo.InstrumentProjects", "Instrument_Id");
            //CreateIndex("dbo.InstrumentProjects", "Project_Id");
            //CreateIndex("dbo.DatasetQAStatus", "Dataset_Id");
            //CreateIndex("dbo.DatasetQAStatus", "QAStatus_Id");
            //CreateIndex("dbo.DatasetQAStatus1", "Dataset_Id");
            //CreateIndex("dbo.DatasetQAStatus1", "QAStatus_Id");
        }
        
        public override void Down()
        {
            //DropIndex("dbo.DatasetQAStatus1", new[] { "QAStatus_Id" });
            //DropIndex("dbo.DatasetQAStatus1", new[] { "Dataset_Id" });
            //DropIndex("dbo.DatasetQAStatus", new[] { "QAStatus_Id" });
            //DropIndex("dbo.DatasetQAStatus", new[] { "Dataset_Id" });
            //DropIndex("dbo.InstrumentProjects", new[] { "Project_Id" });
            //DropIndex("dbo.InstrumentProjects", new[] { "Instrument_Id" });
            //DropIndex("dbo.LocationProjects", new[] { "Project_Id" });
            //DropIndex("dbo.LocationProjects", new[] { "Location_Id" });
            //DropIndex("dbo.ProjectUsers", new[] { "User_Id" });
            //DropIndex("dbo.ProjectUsers", new[] { "Project_Id" });
            //DropIndex("dbo.WaterTemp_Header", new[] { "ByUserId" });
            //DropIndex("dbo.WaterTemp_Header", new[] { "ActivityId" });
            //DropIndex("dbo.WaterTemp_Detail", new[] { "QAStatusId" });
            //DropIndex("dbo.WaterTemp_Detail", new[] { "ByUserId" });
            //DropIndex("dbo.WaterTemp_Detail", new[] { "ActivityId" });
            //DropIndex("dbo.MetadataProperties", new[] { "MetadataEntityId" });
            //DropIndex("dbo.FishTransport_Header", new[] { "ByUserId" });
            //DropIndex("dbo.FishTransport_Header", new[] { "ActivityId" });
            //DropIndex("dbo.FishTransport_Detail", new[] { "QAStatusId" });
            //DropIndex("dbo.FishTransport_Detail", new[] { "ByUserId" });
            //DropIndex("dbo.FishTransport_Detail", new[] { "ActivityId" });
            //DropIndex("dbo.CreelSurvey_Header", new[] { "ByUserId" });
            //DropIndex("dbo.CreelSurvey_Header", new[] { "ActivityId" });
            //DropIndex("dbo.CreelSurvey_Detail", new[] { "QAStatusId" });
            //DropIndex("dbo.CreelSurvey_Detail", new[] { "ByUserId" });
            //DropIndex("dbo.CreelSurvey_Detail", new[] { "ActivityId" });
            //DropIndex("dbo.CreelSurvey_Detail", new[] { "DetailLocationId" });
            //DropIndex("dbo.CreelSurvey_Carcass", new[] { "QAStatusId" });
            //DropIndex("dbo.CreelSurvey_Carcass", new[] { "ByUserId" });
            //DropIndex("dbo.CreelSurvey_Carcass", new[] { "ActivityId" });
            //DropIndex("dbo.ArtificialProduction_Header", new[] { "ByUserId" });
            //DropIndex("dbo.ArtificialProduction_Header", new[] { "ActivityId" });
            //DropIndex("dbo.ArtificialProduction_Detail", new[] { "QAStatusId" });
            //DropIndex("dbo.ArtificialProduction_Detail", new[] { "ByUserId" });
            //DropIndex("dbo.ArtificialProduction_Detail", new[] { "ActivityId" });
            //DropIndex("dbo.Appraisal_Header", new[] { "ByUserId" });
            //DropIndex("dbo.Appraisal_Header", new[] { "ActivityId" });
            //DropIndex("dbo.Appraisal_Detail", new[] { "QAStatusId" });
            //DropIndex("dbo.Appraisal_Detail", new[] { "ByUserId" });
            //DropIndex("dbo.Appraisal_Detail", new[] { "ActivityId" });
            //DropIndex("dbo.AdultWeir_Header", new[] { "ByUserId" });
            //DropIndex("dbo.AdultWeir_Header", new[] { "ActivityId" });
            //DropIndex("dbo.AdultWeir_Detail", new[] { "QAStatusId" });
            //DropIndex("dbo.AdultWeir_Detail", new[] { "ByUserId" });
            //DropIndex("dbo.AdultWeir_Detail", new[] { "ActivityId" });
            //DropIndex("dbo.ActivityQAs", new[] { "UserId" });
            //DropIndex("dbo.ActivityQAs", new[] { "QAStatusId" });
            //DropIndex("dbo.Fields", new[] { "FieldCategoryId" });
            //DropIndex("dbo.DatasetFields", new[] { "InstrumentId" });
            //DropIndex("dbo.DatasetFields", new[] { "SourceId" });
            //DropIndex("dbo.DatasetFields", new[] { "FieldRoleId" });
            //DropIndex("dbo.DatasetFields", new[] { "FieldId" });
            //DropIndex("dbo.DatasetFields", new[] { "DatasetId" });
            //DropIndex("dbo.Datasets", new[] { "DatastoreId" });
            //DropIndex("dbo.Datasets", new[] { "DefaultRowQAStatusId" });
            //DropIndex("dbo.Activities", new[] { "PostAccuracyCheckId" });
            //DropIndex("dbo.Activities", new[] { "AccuracyCheckId" });
            //DropIndex("dbo.Activities", new[] { "InstrumentId" });
            //DropIndex("dbo.Activities", new[] { "ActivityTypeId" });
            //DropIndex("dbo.Activities", new[] { "UserId" });
            //DropIndex("dbo.Activities", new[] { "LocationId" });
            //DropIndex("dbo.Activities", new[] { "SourceId" });
            //DropIndex("dbo.Activities", new[] { "DatasetId" });
            //DropIndex("dbo.Locations", new[] { "SdeFeatureClassId" });
            //DropIndex("dbo.Locations", new[] { "WaterBodyId" });
            //DropIndex("dbo.Locations", new[] { "LocationTypeId" });
            //DropIndex("dbo.Files", new[] { "FileTypeId" });
            //DropIndex("dbo.Files", new[] { "UserId" });
            //DropIndex("dbo.Files", new[] { "ProjectId" });
            //DropIndex("dbo.UserPreferences", new[] { "UserId" });
            //DropIndex("dbo.Users", new[] { "DepartmentId" });
            //DropIndex("dbo.Users", new[] { "OrganizationId" });
            //DropIndex("dbo.Projects", new[] { "OwnerId" });
            //DropIndex("dbo.Projects", new[] { "OrganizationId" });
            //DropIndex("dbo.Projects", new[] { "ProjectTypeId" });
            //DropIndex("dbo.Departments", new[] { "OrganizationId" });
            //DropIndex("dbo.Instruments", new[] { "UserId" });
            //DropIndex("dbo.Instruments", new[] { "InstrumentTypeId" });
            //DropIndex("dbo.Instruments", new[] { "OwningDepartmentId" });
            //DropIndex("dbo.InstrumentAccuracyChecks", new[] { "UserId" });
            //DropIndex("dbo.InstrumentAccuracyChecks", new[] { "InstrumentId" });
            //DropPrimaryKey("dbo.InstrumentProjects");
            //AddPrimaryKey("dbo.InstrumentProjects", new[] { "Project_Id", "Instrument_Id" });
            //RenameTable(name: "dbo.InstrumentProjects", newName: "ProjectInstruments");
        }
    }
}
