// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddWatQualHeaderComments : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWatQualHeaderComments));
        
        string IMigrationMetadata.Id
        {
            get { return "201605042044519_AddWatQualHeaderComments"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
