// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class WaterTemp_AddDischargeField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(WaterTemp_AddDischargeField));
        
        string IMigrationMetadata.Id
        {
            get { return "201809261457343_WaterTemp_AddDischargeField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
