// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class age_dataset1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(age_dataset1));
        
        string IMigrationMetadata.Id
        {
            get { return "201812031746109_age_dataset1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
