// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AlreadyRemovedTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlreadyRemovedTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201807171641140_AlreadyRemovedTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
