// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MetricsUpdView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MetricsUpdView));
        
        string IMigrationMetadata.Id
        {
            get { return "201802091829502_MetricsUpdView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
