// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class transmitter_type_dbcolumnname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(transmitter_type_dbcolumnname));
        
        string IMigrationMetadata.Id
        {
            get { return "201904302108161_transmitter_type_dbcolumnname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
