// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fixed_decimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fixed_decimal));
        
        string IMigrationMetadata.Id
        {
            get { return "201901042150269_fixed_decimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
