// <auto-generated />
namespace services.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class radio_tag_field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(radio_tag_field));
        
        string IMigrationMetadata.Id
        {
            get { return "201904302129581_radio_tag_field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
