update metadataproperties set controltype = 'hidden' where id in (11,13,25,26);
update metadataproperties set controltype = 'text' where id in (22);
update metadataproperties set controltype = 'textarea' where id in (1,3,4,5,9,14,15,20);

DECLARE @entityid int = 0;
insert into metadataentities (name, description) values ('Correspondence','CRPP Correspondence lookup fields');
select @entityid = scope_identity();

insert into metadataproperties (MetadataEntityId, Name, Description, DataType, PossibleValues, ControlType) values 
(@entityid, 'Agency','Agency','string','[]','select'),
(@entityid, 'County','County','string','[]','select'),
(@entityid, 'CorrespondenceType','Correspondence Type','string','[]','select'),
(@entityid, 'ResponseType','Response Type','string','[]','select'),
(@entityid, 'NumberOfDays','Number Of Days','number','[]','select'),
(@entityid, 'StaffMember','Staff Member','string','[]','select'),
(@entityid, 'ProjectLead','Project Lead','string','[]','number-select');

update metadataproperties set PossibleValues = 
'[
"ACHP",
"Anderson Perry",
"Army",
"Baker County",
"Benton County",
"BIA",
"BLM",
"Blue Mountain Ranger District",
"BNSF",
"BOR",
"BPA",
"Camas",
"CenturyLink",
"Clark County",
"College Place",
"Columbia County",
"Corps Portland District",
"Corps Regulatory",
"Corps Walla Walla District",
"CRGNSA",
"CTUIR",
"DAHP",
"DECD",
"Department of Ecology",
"DEQ",
"DOE",
"DOGAMI",
"DSL",
"EPA",
"FAA",
"FCC",
"Federal Transit Authority",
"FEMA",
"FERC",
"FHWA",
"Fisheries",
"Fort Vancouver (NPS)",
"Franklin County",
"FSA",
"Hells Canyon NRA",
"Heppner Ranger District",
"Hermiston",
"Hood River County",
"HUD",
"Idaho Power",
"Irrigon",
"John Day Fossil Beds (NPS)",
"Kennewick",
"Klickitat County",
"La Grande Ranger District",
"Landowner",
"Malheur National Forest",
"Morrow County",
"Navy",
"Nez Perce National Historical Park (NPS)",
"North Fork John Day Ranger District",
"Northwest Pipeline",
"NPS",
"NRCS",
"ODEQ",
"ODOE",
"ODOT",
"OPRD",
"Oregon City",
"Oregon Military Department/Oregon Army National Guard",
"Other",
"OWRD",
"PacifiCorp",
"Pasco",
"PGE",
"Planning Dept",
"Pomeroy Ranger District",
"Port of Benton",
"Port of Clarkston",
"Port of Columbia",
"Port of Kennewick",
"Port of Morrow",
"Port of Umatilla",
"Port of Walla Walla",
"Public Works",
"RAF",
"Recreation and Conservation Office",
"Richland",
"Rural Development",
"RUS",
"SHPO Oregon",
"Skamania County",
"Skamania County PUD",
"Umatilla County",
"Umatilla National Forest",
"UPRR",
"USACE",
"USFWS",
"VA",
"Vancouver",
"Walla Walla City",
"Walla Walla County",
"Walla Walla Ranger District",
"Wallowa County",
"Wallowa Valley Ranger District",
"Wallowa-Whitman National Forest",
"Wasco County",
"Washington Department of Commerce",
"Washington Department of Health",
"Washington Department of Natural Resources",
"Washington State Parks",
"Water Resources",
"WDFW",
"Western Federal Lands Highway Division",
"Whitman Mission (NPS)",
"Whitman Unit",
"Wildhorse Resort and Casino (WRC)",
"Wildlife",
"WSDOT",
"Yellowstone National Park"
]' where name = 'Agency';

update metadataproperties set PossibleValues = 
'[
"Asotin",
"Baker",
"Benton",
"Clark",
"Columbia",
"Franklin",
"Garfield",
"Gilliam",
"Grant, WA",
"Grant, OR",
"Hood River",
"Klickitat",
"Malheur",
"Morrow",
"Multnomah",
"Other",
"Sherman",
"Skamania",
"Umatilla",
"Union",
"Walla Walla",
"Wallowa",
"Wasco",
"Wheeler",
"Whitman"]' where name = 'County';

update metadataproperties set PossibleValues = 
'["Project Notification",
"Notice of Application",
"Seeking Concurrence",
"Document Review",
"Permit Review",
"Sending materials for our records",
"Other"]' where name = 'CorrespondenceType';

update metadataproperties set PossibleValues = 
'["APE letter",
"Asked to be consulting party",
"Defer to other tribe(s)",
"Determination of Eligibility",
"Did not review",
"Emailed Comments",
"Finding of Effect",
"Issued survey/excavation permit",
"Let it go",
"Missed opportunity to review",
"NAGPRA FR Notice",
"NAGPRA inventory/summary",
"none--ok",
"Notice of Application",
"Other",
"Out of area",
"Permit Application",
"Report for Review",
"Requested a monitor",
"Requested a survey",
"Requested additional information",
"Requested report",
"Requested testing",
"Response to comments",
"Reviewed report",
"Same as previously reviewed project",
"Sent letter",
"Signed off on",
"Simple Notification"]' where name = 'ResponseType';

update metadataproperties set PossibleValues = 
'["Bambi Rodriguez",
"Shawn Steinmetz",
"Catherine Dickson",
"Carey Miller",
"Jennifer Karson Engum",
"Shari Sheoships",
"Arthur Van Pelt",
"Teara Farrow Ferman",
"Holly Shea Barrick",
"Wilbur Barrick",
"Dara Williams-Worden",
"Julie Longenecker",
"Julius Patrick",
"Kristen Tiede"]' where name = 'StaffMember';

update metadataproperties set PossibleValues = 
'["Bambi Rodriguez",
"Carey Miller",
"Catherine Dickson",
"Kristen Tiede",
"Shawn Steinmetz",
"Arthur Van Pelt",
"Dara Williams-Worden",
"Jennifer Karson Engum",
"Julius Patrick",
"Shari Sheoships",
"Teara Farrow Ferman"]' where name = 'ProjectLead';
